// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4itUYbLa-YRlyzg9E5rUgEfNHS8A2lWs',
    appId: '1:679531876538:web:c7fdaae5aca92f37cef283',
    messagingSenderId: '679531876538',
    projectId: 'carenepal-cf3ec',
    authDomain: 'carenepal-cf3ec.firebaseapp.com',
    storageBucket: 'carenepal-cf3ec.firebasestorage.app',
    measurementId: 'G-EHVEJG0Y39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Zt7g9-2uyYDj7U7C94J948CCV4X_9hE',
    appId: '1:679531876538:android:99969124692a4111cef283',
    messagingSenderId: '679531876538',
    projectId: 'carenepal-cf3ec',
    storageBucket: 'carenepal-cf3ec.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb6PF6DMa6LVUpXrsVfq-b4kdSx8dYDiU',
    appId: '1:679531876538:ios:31eabd60e5800e18cef283',
    messagingSenderId: '679531876538',
    projectId: 'carenepal-cf3ec',
    storageBucket: 'carenepal-cf3ec.firebasestorage.app',
    iosBundleId: 'com.example.nepalCare',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb6PF6DMa6LVUpXrsVfq-b4kdSx8dYDiU',
    appId: '1:679531876538:ios:31eabd60e5800e18cef283',
    messagingSenderId: '679531876538',
    projectId: 'carenepal-cf3ec',
    storageBucket: 'carenepal-cf3ec.firebasestorage.app',
    iosBundleId: 'com.example.nepalCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4itUYbLa-YRlyzg9E5rUgEfNHS8A2lWs',
    appId: '1:679531876538:web:28e5facf7146a907cef283',
    messagingSenderId: '679531876538',
    projectId: 'carenepal-cf3ec',
    authDomain: 'carenepal-cf3ec.firebaseapp.com',
    storageBucket: 'carenepal-cf3ec.firebasestorage.app',
    measurementId: 'G-2XF7TDW1BL',
  );
}
